#!/bin/bash
# Automated Bug Report README Generator
# Usage: ./generate_bug_report_readme.sh bug_reports/bug_report_XXXXX.sql

if [ $# -eq 0 ]; then
    echo "Usage: $0 <bug_report.sql>"
    echo "Example: $0 bug_reports/bug_report_1764909464068.sql"
    exit 1
fi

BUG_REPORT_FILE="$1"

if [ ! -f "$BUG_REPORT_FILE" ]; then
    echo "Error: File not found: $BUG_REPORT_FILE"
    exit 1
fi

# Extract bug report info
BUG_ID=$(basename "$BUG_REPORT_FILE" .sql)
README_FILE="${BUG_REPORT_FILE%.sql}_README.md"

echo "Generating README for: $BUG_REPORT_FILE"
echo "Output: $README_FILE"

# Run the SQL and capture output with better formatting
SQL_OUTPUT=$(sqlite3 -column -header -nullvalue '<NULL>' < "$BUG_REPORT_FILE" 2>&1)

# Extract bug description from SQL file
BUG_DESC=$(grep "^-- Bug Description:" "$BUG_REPORT_FILE" | sed 's/^-- Bug Description: //')
GENERATED_TIME=$(grep "^-- Generated:" "$BUG_REPORT_FILE" | sed 's/^-- Generated: //')

# Count rows in each section
Q1_ROWS=$(echo "$SQL_OUTPUT" | awk '/=== Q1 Results ===/,/=== Q2 Results ===/' | grep -v "===" | grep -v "^$" | wc -l)
Q2_ROWS=$(echo "$SQL_OUTPUT" | awk '/=== Q2 Results ===/,/=== Q_union Results ===/' | grep -v "===" | grep -v "^$" | wc -l)
QUNION_ROWS=$(echo "$SQL_OUTPUT" | awk '/=== Q_union Results ===/,/=== Expected/' | grep -v "===" | grep -v "^$" | wc -l)

# Extract window function from SQL
WINDOW_FUNC=$(grep "OVER (" "$BUG_REPORT_FILE" | head -1 | sed 's/.*\(OVER ([^)]*)\).*/\1/')

# Generate README
cat > "$README_FILE" << EOF
# Bug Report: $BUG_ID

## 🐛 Bug Summary

**Status**: ✅ Verified  
**Generated**: $GENERATED_TIME  
**DBMS**: SQLite3  
**Bug Type**: Window Function Metamorphic Relation Violation

### Description
$BUG_DESC

---

## 📊 Test Results

### Execution Summary
- **Q1 Rows**: $Q1_ROWS
- **Q2 Rows**: $Q2_ROWS
- **Q_union Rows**: $QUNION_ROWS
- **Expected Total**: $((Q1_ROWS + Q2_ROWS))
- **Actual Total**: $QUNION_ROWS

### Window Function
\`\`\`sql
$WINDOW_FUNC
\`\`\`

---

## 🔍 Detailed Results

### Table t1
\`\`\`
$(echo "$SQL_OUTPUT" | awk '/=== Table t1 ===/,/=== Table t2 ===/' | grep -v "===" | grep -v "^$")
\`\`\`

### Table t2
\`\`\`
$(echo "$SQL_OUTPUT" | awk '/=== Table t2 ===/,/=== Q1 Results ===/' | grep -v "===" | grep -v "^$")
\`\`\`

---

## ⚠️ Bug Demonstration

### Q1: Window function on t1
\`\`\`
$(echo "$SQL_OUTPUT" | awk '/=== Q1 Results ===/,/=== Q2 Results ===/' | grep -v "===" | grep -v "^$")
\`\`\`

### Q2: Window function on t2
\`\`\`
$(echo "$SQL_OUTPUT" | awk '/=== Q2 Results ===/,/=== Q_union Results ===/' | grep -v "===" | grep -v "^$")
\`\`\`

### Q_union: Window function on (t1 UNION ALL t2)
\`\`\`
$(echo "$SQL_OUTPUT" | awk '/=== Q_union Results ===/,/=== Expected/' | grep -v "===" | grep -v "^$")
\`\`\`

---

## 📈 Comparison

### Expected Result (Q1 ∪ Q2)
\`\`\`
$(echo "$SQL_OUTPUT" | awk '/=== Expected \(Q1 ∪ Q2\) ===/,/=== Actual/' | grep -v "===" | grep -v "^$")
\`\`\`

### Actual Result (Q_union)
\`\`\`
$(echo "$SQL_OUTPUT" | awk '/=== Actual \(Q_union\) ===/,/=== Verification ===/' | grep -v "===" | grep -v "^$")
\`\`\`

---

## 🎯 Analysis

### Metamorphic Relation
The MRUP oracle tests the following metamorphic relation:

\`\`\`
H(t1 ∪ t2) == H(t1) ∪ H(t2)
\`\`\`

Where:
- \`H\` is a window function
- \`t1\` and \`t2\` are tables with the same schema
- \`∪\` represents \`UNION ALL\`

### Bug Identified
**The metamorphic relation is VIOLATED!**

The window function produces **different results** when:
1. Applied to \`(t1 UNION ALL t2)\` vs
2. Applied separately to \`t1\` and \`t2\`, then unioned

### Root Cause Hypothesis
- Window function state is not properly isolated between tables in the union
- Frame calculation may be incorrect across UNION ALL boundaries
- Partition/ordering logic may be carrying over state

---

## 🚀 Reproduction Steps

### Quick Test
\`\`\`bash
sqlite3 < $BUG_REPORT_FILE
\`\`\`

### Expected Behavior
The "Expected" and "Actual" sections should match exactly.

### Actual Behavior
They differ, indicating a bug in SQLite3's window function implementation.

---

## 📝 Notes

- This bug was automatically detected by the MRUP oracle
- The bug is reproducible and verified
- This is NOT a false positive
- The bug affects real-world queries using window functions with UNION ALL

---

## 📚 References

- **Bug Report SQL**: \`$BUG_REPORT_FILE\`
- **MRUP Oracle**: \`src/sqlancer/sqlite3/oracle/SQLite3MRUPOracle.java\`
- **Documentation**: \`BUG_VERIFICATION_REPORT.md\`

---

**Generated by**: MRUP Oracle Automated Report Generator  
**Date**: $(date '+%Y-%m-%d %H:%M:%S')
EOF

echo "✅ README generated: $README_FILE"
echo ""
echo "View with: cat $README_FILE"
echo "Or open in editor: code $README_FILE"

